### ISSUE TITLE
Editable install won't run

### ISSUE THREAD

**Issue by jotelha** [libAtoms/matscipy#191]
When I install the current master editable (Python 3.8), the import of matscipy fails with the `FileNotFoundError` below.

```console
jotelha@jotelha-fujitsu-ubuntu-20:~/git/matscipy$ python3 -m venv venv
jotelha@jotelha-fujitsu-ubuntu-20:~/git/matscipy$ source venv/bin/activate
(venv) jotelha@jotelha-fujitsu-ubuntu-20:~/git/matscipy$ pip install --upgrade pip
Collecting pip
  Using cached pip-23.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-23.3
(venv) jotelha@jotelha-fujitsu-ubuntu-20:~/git/matscipy$ pip install -e .
Obtaining file:///home/jotelha/git/matscipy
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting numpy>=1.16.0 (from matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting scipy>=1.2.3 (from matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting ase>=3.16.0 (from matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached ase-3.22.1-py3-none-any.whl (2.2 MB)
Collecting matplotlib>=3.1.0 (from ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached matplotlib-3.7.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (5.7 kB)
Collecting contourpy>=1.0.1 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.9 kB)
Collecting cycler>=0.10 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached fonttools-4.43.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (152 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (6.4 kB)
Collecting packaging>=20.0 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pillow>=6.2.0 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached Pillow-10.1.0-cp38-cp38-manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Collecting pyparsing>=2.3.1 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting importlib-resources>=3.2.0 (from matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached importlib_resources-6.1.0-py3-none-any.whl.metadata (4.1 kB)
Collecting zipp>=3.1.0 (from importlib-resources>=3.2.0->matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib>=3.1.0->ase>=3.16.0->matscipy==0.8.0.dev329+ga8c9482.dirty)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Using cached matplotlib-3.7.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
Using cached contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.43.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Using cached importlib_resources-6.1.0-py3-none-any.whl (33 kB)
Using cached kiwisolver-1.4.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached Pillow-10.1.0-cp38-cp38-manylinux_2_28_x86_64.whl (3.6 MB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Building wheels for collected packages: matscipy
  Building editable for matscipy (pyproject.toml) ... done
  Created wheel for matscipy: filename=matscipy-0.8.0.dev329+ga8c9482.dirty-cp38-cp38-linux_x86_64.whl size=73450 sha256=51af14ab9783dbf12276f50db99f14f59444b5a26c3a5f7011014af4dd6a6e56
  Stored in directory: /tmp/pip-ephem-wheel-cache-x6ujkdmi/wheels/5c/35/8a/1825ff9711804919e6bd4df19ca252b1416fd8ebe54f6a3cd9
Successfully built matscipy
Installing collected packages: zipp, six, pyparsing, pillow, packaging, numpy, kiwisolver, fonttools, cycler, scipy, python-dateutil, importlib-resources, contourpy, matplotlib, ase, matscipy
Successfully installed ase-3.22.1 contourpy-1.1.1 cycler-0.12.1 fonttools-4.43.1 importlib-resources-6.1.0 kiwisolver-1.4.5 matplotlib-3.7.3 matscipy-0.8.0.dev329+ga8c9482.dirty numpy-1.24.4 packaging-23.2 pillow-10.1.0 pyparsing-3.1.1 python-dateutil-2.8.2 scipy-1.10.1 six-1.16.0 zipp-3.17.0
WARNING: There was an error checking the latest version of pip.
(venv) jotelha@jotelha-fujitsu-ubuntu-20:~/git/matscipy$ pip freeze
ase==3.22.1
contourpy==1.1.1
cycler==0.12.1
fonttools==4.43.1
importlib-resources==6.1.0
kiwisolver==1.4.5
matplotlib==3.7.3
-e git+https://github.com/libAtoms/matscipy.git@a8c94826f908c63e75ac736cbb7624ccbb463356#egg=matscipy
numpy==1.24.4
packaging==23.2
Pillow==10.1.0
pkg_resources==0.0.0
pyparsing==3.1.1
python-dateutil==2.8.2
scipy==1.10.1
six==1.16.0
zipp==3.17.0
(venv) jotelha@jotelha-fujitsu-ubuntu-20:~/git/matscipy$ python -c 'import matscipy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/home/jotelha/git/matscipy/venv/lib/python3.8/site-packages/_matscipy_editable_loader.py", line 271, in find_spec
    tree = self.rebuild()
  File "/home/jotelha/git/matscipy/venv/lib/python3.8/site-packages/_matscipy_editable_loader.py", line 312, in rebuild
    subprocess.run(self._build_cmd, cwd=self._build_path, env=env, stdout=stdout, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-env-hpofqal0/overlay/bin/ninja'
```

I haven't run into that issue before. I put this here as a note to myself to look into it further.

**Comment by jameskermode** [comment]
Can be solved by adding the `--no-build-isolation` flag to `pip install -e` command.

See https://meson-python.readthedocs.io/en/latest/how-to-guides/editable-installs.html
