### ISSUE TITLE
TST: electrochemistry CLI pipe output test fails in CI ...

### ISSUE THREAD

**Issue by jotelha** [libAtoms/matscipy#219]
... and apparently succeeds sometimes and fails sometimes locally.

https://github.com/libAtoms/matscipy/blob/ba2179106680a102d4510d2be1bdf8374c3be645/tests/test_electrochemistry_cli.py#L175-L200

When it fails, it does so because `continuous2discrete` exits with a non-zero code,

```

self = <test_electrochemistry_cli.ElectrochemistryCliTest testMethod=test_pnp_c2d_pipeline_mode>

    def test_pnp_c2d_pipeline_mode(self):
        """poisson-nernst-planck -c 0.1 0.1 -u 0.05 -l 1.0e-7 -bc cell | continuous2discrete > NaCl.xyz"""
        print("  RUN test_pnp_c2d_pipeline_mode")
        with tempfile.TemporaryDirectory() as tmpdir:
            pnp = subprocess.Popen(
                ['pnp', '-c', '0.1', '0.1', '-z', '1', '-1',
                    '-u', '0.05', '-l', '1.0e-7', '-bc', 'cell'],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                cwd=tmpdir, encoding='utf-8', env=self.myenv)
    
            c2d = subprocess.Popen([ 'c2d' ],
                stdin=pnp.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                cwd=tmpdir, encoding='utf-8', env=self.myenv)
            pnp.stdout.close()  # Allow pnp to receive a SIGPIPE if p2 exits.
    
>           self.assertEqual(c2d.wait(),0)

test_electrochemistry_cli.py:190: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
matscipytest.py:91: in assertEqual
    self.fail('%s != %s' % (a,b))
E   AssertionError: 1 != 0
-----------------------------------
```

**Comment by jotelha** [comment]
Looking at the two chained commands' stderr in CI now, there are a) warnings about the numpy & scipy version, and b) an error on reading from stdout in the second chained command. This looks like stdout is polluted by some plain text again, as had been the case in https://github.com/libAtoms/matscipy/issues/211. 

```
______________ ElectrochemistryCliTest.test_pnp_c2d_pipeline_mode ______________

self = <test_electrochemistry_cli.ElectrochemistryCliTest testMethod=test_pnp_c2d_pipeline_mode>

    def test_pnp_c2d_pipeline_mode(self):
        """poisson-nernst-planck -c 0.1 0.1 -u 0.05 -l 1.0e-7 -bc cell | continuous2discrete > NaCl.xyz"""
        print("  RUN test_pnp_c2d_pipeline_mode")
        with tempfile.TemporaryDirectory() as tmpdir:
            pnp = subprocess.Popen(
                ['pnp', '-c', '0.1', '0.1', '-z', '1', '-1',
                    '-u', '0.05', '-l', '1.0e-7', '-bc', 'cell'],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                cwd=tmpdir, encoding='utf-8', env=self.myenv)
    
            c2d = subprocess.Popen(['c2d'],
                stdin=pnp.stdout, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                cwd=tmpdir, encoding='utf-8', env=self.myenv)
            pnp.stdout.close()  # Allow pnp to receive a SIGPIPE if p2 exits.
    
            print("  poisson-nernst-planck stderr")
            print(pnp.stderr.read())
            print("  poisson-nernst-planck stderr")
            print(c2d.stderr.read())
    
>           self.assertEqual(c2d.wait(),0)

test_electrochemistry_cli.py:195: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
matscipytest.py:91: in assertEqual
    self.fail('%s != %s' % (a,b))
E   AssertionError: 1 != 0
----------------------------- Captured stdout call -----------------------------
  RUN test_pnp_c2d_pipeline_mode
  poisson-nernst-planck stderr
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

  poisson-nernst-planck stderr
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
ValueError: could not convert string to float: 'Calling'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/tmpty526hk4/c2d", line 312, in <module>
    main()
  File "/tmp/tmpty526hk4/c2d", line 208, in main
    data = np.loadtxt(infile, unpack=True)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 1016, in _read
    arr = _load_from_filelike(
ValueError: could not convert string 'Calling' to float64 at row 0, column 1.
```

WIll inspect content of stdout next.

**Comment by jotelha** [comment]
The culprit are again fenics messages being printed to stdout, now have to figure out why that still happens in CI,

https://github.com/libAtoms/matscipy/actions/runs/7519293192/job/20467663371#step:6:951

**Comment by jotelha** [comment]
Resolved with https://github.com/libAtoms/matscipy/pull/218
